# Generated by Django 6.0.5 on 2026-07-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpu_threshold',
            field=models.FloatField(default=90.0),
        ),
        migrations.AddField(
            model_name='user',
            name='disk_threshold',
            field=models.FloatField(default=95.0),
        ),
        migrations.AddField(
            model_name='user',
            name='enable_desktop_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='enable_email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='heartbeat_timeout',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='user',
            name='memory_threshold',
            field=models.FloatField(default=90.0),
        ),
        migrations.AddField(
            model_name='user',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
