# Generated by Django 6.0.5 on 2026-07-19 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_cpu_threshold_user_disk_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member_role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('OPERATOR', 'Operator'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ORGANIZATION_ADMIN', 'Organization Admin'), ('MEMBER', 'Member')], default='INDIVIDUAL', max_length=30),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('alert_email', models.EmailField(max_length=254)),
                ('alert_recipients', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='users.organization'),
        ),
    ]
